<div style="background-color: RGB(0,0,0);" >
<h1 style="margin: auto; padding: 20px; color:RGB(255,255,255); text-align: center">NOTEBOOK - Stéphane Srsa</h1>   
<h1 style="margin: auto; padding: 20px; color:RGB(255,255,255); text-align: center">PROJET 9</h1>
<h2 style="margin: auto; padding: 20px; color:RGB(255,255,255); text-align: center">Produire une étude de marché avec Python</h2>
</div>      
    
<div style="text-align:center; background-color: RGB(0,0,0);">
    <img src="crazy_chicken.jpg" alt="Crazy Chicken" width="800" height="400">
</div>
<div style="background-color: RGB(0,0,0);" > 
    
<h1 style="margin: auto; padding: 30px; color:RGB(51,153,153); text-align: center ">SOMMAIRE - Partie I</h1>  
    
 - <a href="#C1" style="margin: auto; line-height: 2.5; padding: 20px; color:RGB(255,255,255); font-size: 20px; font-weight: bold;">1 - Importation des librairies et des fichiers</a>
    
    
 - <a href="#C2" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">1.1 - Importation des librairies</a> 
 - <a href="#C3" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">1.2 - Importation des éléments de la librairie 'Scikit'</a>     
 - <a href="#C4" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">1.3 - Importation des fichiers</a>
 - <a href="#C5" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">1.4 - Importation des fonctions</a>   
    
 - <a href="#C6" style="margin: auto; line-height: 2.5; padding: 20px; color:RGB(255,255,255); font-size: 20px; font-weight: bold;">2 - Analyse exploratoire des fichiers</a>
    
 - <a href="#C7" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">2.1 - Analyse exploratoire du fichier "Table_Volaille"</a>
 - <a href="#C8" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">2.2 - Analyse exploratoire du fichier "Pop_Evol"</a>
 - <a href="#C9" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">2.3 - Analyse exploratoire du fichier 'PIB_Hab'</a>
 - <a href="#C10" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">2.4 - Analyse exploratoire du fichier 'Prix_Prod_Poulet'</a>
 - <a href="#C11" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">2.5 - Analyse exploratoire du fichier 'StabPol_PIB'</h4>
 - <a href="#C12" style="margin-left: 40px; color: RGB(51,153,153); font-size: 16px;">2.6 - Analyse exploratoire du fichier 'Protein'</a> 
    
 - <a href="#C13" style="margin: auto; line-height: 2.5; padding: 20px; color:RGB(255,255,255); font-size: 20px; font-weight: bold;">3 - Sauvegarde des tables nettoyées et préparées</a>   
    
 - <a href="#C14" style="margin: auto; line-height: 2.5; padding: 20px; color:RGB(255,255,255); font-size: 20px; font-weight: bold;">4 - Jointures des tables</a>
</div>

<div style="background-color: RGB(0,0,0); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(51,153,153);padding: 5px;">
    <a name="C1" style="margin: auto; padding: 20px; line-height: 2.5; color:RGB(51,153,153); font-size: 20px; font-weight: bold;" >1 - Importation des librairies et chargement des fichiers</a>
</div>

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;">
    <a name="C2" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>1.1 - Importation des librairies</strong></a>
</div>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, HTML
from tabulate import tabulate

# Pour palier aux avertissements à l'utilisation de Seaborn (entre autres)
import warnings
warnings.filterwarnings("ignore")

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;" >
    <a name="C3" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>1.2 - Importation des éléments de la librairie 'Scikit'</strong></a>
</div>

In [2]:
from scipy import stats
from sklearn import decomposition
from sklearn import preprocessing
from sklearn.impute import KNNImputer
from sklearn.cluster import KMeans
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn.cluster import AgglomerativeClustering
from sklearn.ensemble import IsolationForest

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;" >
    <a name="C4" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>1.3 - Importation des fichiers</strong></a>
</div>

In [3]:
# Source: FAOSTAT, Mise à jour 2023-10-27
Table_Volaille = pd.read_csv('Dispo_Alim2010-.csv', sep=';') 

# Source: FAOSTAT, Mise à jour 2022-11-10
Pop_Evol = pd.read_csv('Evol_Demo2000.csv', sep=';')
Prix_Prod_Poulet = pd.read_csv('Prix_Prod_Poulet.csv', sep=';')

# Source: FAOSTAT, Mise à jour 2023-08-23
PIB_Hab = pd.read_csv('PIB_Hab.csv', sep=';')
Protein = pd.read_csv('Proteines.csv', sep=';')

# Source: THE WORLD BANK
StabPol = pd.read_csv('Stabilité politique-TheWorldBank.csv', sep=';')

# Table verif 'Pays'
Pays_Etalon = pd.read_csv('PAYS_ETALON150.csv', sep=';')
Pays_Etalon = Pays_Etalon.rename(columns={'Country_FR': 'Pays'})

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;" >
    <a name="C5" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>1.4 - Importation des fonctions</strong></a>
</div>

In [4]:
from P9_Fonctions_GitHub import *

<div style="background-color: RGB(0,0,0); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(51,153,153);padding: 5px;">
    <a name="C6" style="margin: auto; padding: 20px; line-height: 2.5; color:RGB(51,153,153); font-size: 20px; font-weight: bold;" >2 -Analyse exploratoire des fichiers</a>
</div>

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;" >
    <a name="C7" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>2.1 - Analyse exploratoire du fichier "Table_Volaille"</strong></a>
</div>

In [5]:
message = 'Fichier chargé'
Text_message(message)
display(Table_Volaille.head(2))
display(Table_Volaille.tail(2))
message = 'Traitement du fichier'
Text_message(message)
# Agrégez les colonnes 'Elément' et 'Unité' en une nouvelle colonne 'Items' si nécessaire
Table_Volaille['Items'] = Table_Volaille.apply(lambda row: row['Élément'] + " / " + row['Unité'] if row['Unité'] == 'Milliers de tonnes' else row['Élément'], axis=1)
# Pivoter la table
Table_Volaille= Table_Volaille.pivot(index=['Code zone (M49)', 'Pays','Année'], columns='Items', values='Valeur' )
Table_Volaille = Table_Volaille.reset_index()

# Suppression des colonnes non pertinantes
Table_Volaille.drop(['Alimentation pour touristes / Milliers de tonnes', 'Aliments pour animaux / Milliers de tonnes', 
                     'Autres utilisations (non alimentaire) / Milliers de tonnes',
                             'Pertes / Milliers de tonnes', 'Traitement / Milliers de tonnes'], axis=1, inplace=True)

# Lecture des informations du fichier
infos_DF(Table_Volaille)

   Code zone (M49)         Pays     Élément  Année               Unité  Valeur
0                4  Afghanistan  Production   2010  Milliers de tonnes    28.0
1                4  Afghanistan  Production   2011  Milliers de tonnes    26.0

,Code zone (M49),Pays,Élément,Année,Unité,Valeur
31837,716,Zimbabwe,Disponibilité de matière grasse en quantité (t),2020,tonnes,9016.56
31838,716,Zimbabwe,Disponibilité de matière grasse en quantité (t),2021,tonnes,9355.02

Items,Code zone (M49),Pays,Année,Disponibilité alimentaire (Kcal),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de matière grasse en quantité (t),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité de protéines en quantité (t),Disponibilité intérieure / Milliers de tonnes,Exportations - Quantité / Milliers de tonnes,Importations - Quantité / Milliers de tonnes,Nourriture / Milliers de tonnes,Production / Milliers de tonnes,Résidus / Milliers de tonnes,Variation de stock / Milliers de tonnes
0,4,Afghanistan,2010,88908.07,8.64,2.29,0.50,5150.16,1.03,10625.60,65.0,NaN,39.0,65.0,28.0,0.0,2.0
1,4,Afghanistan,2011,77313.26,7.24,1.92,0.42,4478.51,0.87,9239.88,56.0,NaN,51.0,56.0,26.0,0.0,20.0
2,4,Afghanistan,2012,85969.90,7.73,2.05,0.45,4979.96,0.92,10274.45,62.0,NaN,22.0,62.0,25.0,0.0,-16.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2176 entries, 0 to 2175
Data columns (total 17 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Code zone (M49)                                                2176 non-null   int64
 1   Pays                                                           2176 non-null   object
 2   Année                                                          2176 non-null   int64
 3   Disponibilité alimentaire (Kcal)                               2176 non-null   float64
 4   Disponibilité alimentaire (Kcal/personne/jour)                 2176 non-null   float64
 5   Disponibilité alimentaire en quantité (kg/personne/an)         2176 non-null   float64
 6   Disponibilité de matière grasse en quantité (g/personne/jour)  2176 non-null   float64
 7   Disponibilité de matière grasse en quantité (t)                2176 non-null   float64
 8   Disponibilité de protéines en quantité (g/personne/jour)       2176 non-null   float64
 9   Disponibilité de protéines en quantité (t)                     2176 non-null   float64
 10  Disponibilité intérieure / Milliers de tonnes                  2176 non-null   float64
 11  Exportations - Quantité / Milliers de tonnes                   1772 non-null   float64
 12  Importations - Quantité / Milliers de tonnes                   2171 non-null   float64
 13  Nourriture / Milliers de tonnes                                2176 non-null   float64
 14  Production / Milliers de tonnes                                2152 non-null   float64
 15  Résidus / Milliers de tonnes                                   2176 non-null   float64
 16  Variation de stock / Milliers de tonnes                        2124 non-null   float64
dtypes: float64(14), int64(2), object(1)
memory usage: 289.1+ KB

Items
Code zone (M49)                                                    0
Pays                                                               0
Année                                                              0
Disponibilité alimentaire (Kcal)                                   0
Disponibilité alimentaire (Kcal/personne/jour)                     0
Disponibilité alimentaire en quantité (kg/personne/an)             0
Disponibilité de matière grasse en quantité (g/personne/jour)      0
Disponibilité de matière grasse en quantité (t)                    0
Disponibilité de protéines en quantité (g/personne/jour)           0
Disponibilité de protéines en quantité (t)                         0
Disponibilité intérieure / Milliers de tonnes                      0
Exportations - Quantité / Milliers de tonnes                     404
Importations - Quantité / Milliers de tonnes                       5
Nourriture / Milliers de tonnes                                    0
Production / Milliers de tonnes                                   24
Résidus / Milliers de tonnes                                       0
Variation de stock / Milliers de tonnes                           52
dtype: int64

Items
Code zone (M49)                                                   186
Pays                                                              186
Année                                                              12
Disponibilité alimentaire (Kcal)                                 2176
Disponibilité alimentaire (Kcal/personne/jour)                   2016
Disponibilité alimentaire en quantité (kg/personne/an)           1719
Disponibilité de matière grasse en quantité (g/personne/jour)     962
Disponibilité de matière grasse en quantité (t)                  2174
Disponibilité de protéines en quantité (g/personne/jour)         1343
Disponibilité de protéines en quantité (t)                       2176
Disponibilité intérieure / Milliers de tonnes                     787
Exportations - Quantité / Milliers de tonnes                      308
Importations - Quantité / Milliers de tonnes                      389
Nourriture / Milliers de tonnes                                   766
Production / Milliers de tonnes                                   728
Résidus / Milliers de tonnes                                       63
Variation de stock / Milliers de tonnes                           196
dtype: int64

<div style="border: 10px solid #000; width: 400px; height: 60px; background-color: RGB(110,15,15); margin: 0 auto; ">
    <h3 style="margin: 10px; text-align: center; color: #fafafa;">Concordance des pays</h3>
</div>

In [6]:
# Ajustement des Pays
Pays_absents(Table_Volaille,Pays_Etalon)

Items,Code zone (M49),Pays,Année,Disponibilité alimentaire (Kcal),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de matière grasse en quantité (t),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité de protéines en quantité (t),Disponibilité intérieure / Milliers de tonnes,Exportations - Quantité / Milliers de tonnes,Importations - Quantité / Milliers de tonnes,Nourriture / Milliers de tonnes,Production / Milliers de tonnes,Résidus / Milliers de tonnes,Variation de stock / Milliers de tonnes
0,4,Afghanistan,2010,88908.07,8.64,2.29,0.50,5150.16,1.03,10625.60,65.0,NaN,39.0,65.0,28.0,0.0,2.0
1,4,Afghanistan,2011,77313.26,7.24,1.92,0.42,4478.51,0.87,9239.88,56.0,NaN,51.0,56.0,26.0,0.0,20.0

['Chine' 'Tchéquie' "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord"]

In [7]:
# Mise en conformité des Pays
#Concordance_pays = {"Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": 'Royaume-Uni', 'Tchéquie':'République Tchèque'}
#Table_Volaille['Pays'] = Table_Volaille['Pays'].replace(Concordance_pays)

<div style="border: 10px solid RGB(0,0,0);width: 500px; background-color: RGB(110,15,15); margin: 0 auto; text-align: center;">
<h3 style="margin: 10px; text-align:center; color: RGB(250,250,250); ">Sélection des zones chinoises</h3>
</div>

In [8]:
# Vérification des Pays contenant 'Chine'
filtered_df = Table_Volaille.loc[(Table_Volaille['Pays'].str.contains('Chine')) & (Table_Volaille['Année'] == 2017)]
display(filtered_df)

message = "La Chine englobe 4 zones différentes. Pour les besoins de l'analyse, nous ne conservons que ces 4 zones"
Text_message(message)
message = "Disponibilité alimentaire (Kcal): 30741523.62 = 29052986.09+ 1132461.66 + 524597.74 + 31478.13"
Text_message(message)

# Supprimer la ligne où le pays est 'Chine'
Table_Volaille = Table_Volaille.loc[Table_Volaille['Pays'] != 'Chine']

Items,Code zone (M49),Pays,Année,Disponibilité alimentaire (Kcal),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de matière grasse en quantité (t),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité de protéines en quantité (t),Disponibilité intérieure / Milliers de tonnes,Exportations - Quantité / Milliers de tonnes,Importations - Quantité / Milliers de tonnes,Nourriture / Milliers de tonnes,Production / Milliers de tonnes,Résidus / Milliers de tonnes,Variation de stock / Milliers de tonnes
397,156,"Chine, continentale",2017,29052986.09,56.44,12.73,3.75,1929204.52,5.67,2918322.12,17621.0,576.0,452.0,17957.0,18405.0,-336.0,660.0
409,158,"Chine, Taiwan Province de",2017,1132461.66,131.11,33.44,7.87,67959.55,15.02,129757.46,792.0,8.0,161.0,791.0,657.0,0.0,18.0
421,159,Chine,2017,30741523.62,58.41,13.25,3.86,2029651.39,5.91,3111027.27,18670.0,1249.0,1554.0,19113.0,19090.0,-476.0,725.0
853,344,Chine - RAS de Hong-Kong,2017,524597.74,192.62,46.09,11.22,30566.59,21.82,59439.32,237.0,664.0,917.0,344.0,24.0,-141.0,40.0
1189,446,Chine - RAS de Macao,2017,31478.13,135.05,33.36,8.24,1920.73,15.05,3508.36,21.0,0.0,23.0,21.0,4.0,0.0,6.0

In [9]:
Table_Volaille.isnull().sum()

Items
Code zone (M49)                                                    0
Pays                                                               0
Année                                                              0
Disponibilité alimentaire (Kcal)                                   0
Disponibilité alimentaire (Kcal/personne/jour)                     0
Disponibilité alimentaire en quantité (kg/personne/an)             0
Disponibilité de matière grasse en quantité (g/personne/jour)      0
Disponibilité de matière grasse en quantité (t)                    0
Disponibilité de protéines en quantité (g/personne/jour)           0
Disponibilité de protéines en quantité (t)                         0
Disponibilité intérieure / Milliers de tonnes                      0
Exportations - Quantité / Milliers de tonnes                     404
Importations - Quantité / Milliers de tonnes                       5
Nourriture / Milliers de tonnes                                    0
Production / Milliers de tonnes                                   24
Résidus / Milliers de tonnes                                       0
Variation de stock / Milliers de tonnes                           52
dtype: int64

<div style="border: 10px solid RGB(0,0,0); width: 500px; background-color: RGB(110,15,15); margin: 0 auto; text-align: center;">
    <h3 style="margin: 10px; color: RGB(250,250,250);">Compléter le champs 'Exportations'</h3>
</div>

### Rappel de l'équation:  disponibilité intérieure = Production + Importations - Exportations + Variation de stock
### soit : Exportations = Production + Importations + Variation de stock - disponibilité intérieure

In [10]:
# Remplacer les NaN par la valeur calculée dans 'Exportation'
def calcul_exportations(row):
    if pd.isna(row['Exportations - Quantité / Milliers de tonnes']):
        return (row['Production / Milliers de tonnes'] +
                row['Importations - Quantité / Milliers de tonnes'] +
                row['Variation de stock / Milliers de tonnes'] -
                row['Disponibilité intérieure / Milliers de tonnes'])
    else:
        return row['Exportations - Quantité / Milliers de tonnes']

# Appliquer la formule dans "Exportations - Quantité / Milliers de tonnes"
Table_Volaille['Exportations - Quantité / Milliers de tonnes'] = Table_Volaille.apply(calcul_exportations, axis=1)
Table_Volaille.isnull().sum()

Items
Code zone (M49)                                                   0
Pays                                                              0
Année                                                             0
Disponibilité alimentaire (Kcal)                                  0
Disponibilité alimentaire (Kcal/personne/jour)                    0
Disponibilité alimentaire en quantité (kg/personne/an)            0
Disponibilité de matière grasse en quantité (g/personne/jour)     0
Disponibilité de matière grasse en quantité (t)                   0
Disponibilité de protéines en quantité (g/personne/jour)          0
Disponibilité de protéines en quantité (t)                        0
Disponibilité intérieure / Milliers de tonnes                     0
Exportations - Quantité / Milliers de tonnes                     23
Importations - Quantité / Milliers de tonnes                      5
Nourriture / Milliers de tonnes                                   0
Production / Milliers de tonnes                                  24
Résidus / Milliers de tonnes                                      0
Variation de stock / Milliers de tonnes                          52
dtype: int64

In [11]:
# on peut maintenant supprimer les variations de stocks
Table_Volaille=Table_Volaille.drop('Variation de stock / Milliers de tonnes', axis=1)

In [12]:
# Valeurs manquantes restantes
Table_Volaille[Table_Volaille.isnull().any(axis=1)]

Items,Code zone (M49),Pays,Année,Disponibilité alimentaire (Kcal),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de matière grasse en quantité (t),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité de protéines en quantité (t),Disponibilité intérieure / Milliers de tonnes,Exportations - Quantité / Milliers de tonnes,Importations - Quantité / Milliers de tonnes,Nourriture / Milliers de tonnes,Production / Milliers de tonnes,Résidus / Milliers de tonnes
678,262,Djibouti,2010,1857.00,5.53,1.47,0.32,107.57,0.66,221.93,1.0,0.0,1.0,1.0,NaN,0.0
679,262,Djibouti,2011,983.61,2.88,0.76,0.17,56.98,0.34,117.55,1.0,0.0,1.0,1.0,NaN,0.0
680,262,Djibouti,2012,6341.09,18.20,4.82,1.05,367.32,2.18,757.84,5.0,0.0,5.0,5.0,NaN,0.0
681,262,Djibouti,2013,2471.41,6.97,1.85,0.40,143.16,0.83,295.36,2.0,0.0,2.0,2.0,NaN,0.0
682,262,Djibouti,2014,1812.34,5.02,1.32,0.29,104.56,0.60,216.03,1.0,NaN,1.0,1.0,NaN,0.0
683,262,Djibouti,2015,2735.65,7.45,1.96,0.43,157.95,0.89,326.14,2.0,NaN,2.0,2.0,NaN,0.0
684,262,Djibouti,2016,2697.71,7.22,1.90,0.42,155.91,0.86,321.60,2.0,NaN,2.0,2.0,NaN,0.0
685,262,Djibouti,2017,3851.53,10.14,2.68,0.60,226.20,1.18,449.88,3.0,NaN,3.0,3.0,NaN,0.0
686,262,Djibouti,2018,4414.02,11.44,3.02,0.66,255.32,1.36,526.66,3.0,NaN,3.0,3.0,NaN,0.0
687,262,Djibouti,2019,4951.77,12.63,3.33,0.73,286.42,1.51,590.89,4.0,NaN,4.0,4.0,NaN,0.0
688,262,Djibouti,2020,4979.69,12.51,3.30,0.72,287.29,1.50,595.06,4.0,NaN,4.0,4.0,NaN,0.0
689,262,Djibouti,2021,6480.82,16.06,4.21,0.93,373.74,1.91,772.29,5.0,NaN,5.0,5.0,NaN,0.0
1038,408,République populaire démocratique de Corée,2010,63179.57,7.01,1.72,0.44,3967.30,0.76,6864.20,43.0,NaN,NaN,43.0,43.0,0.0
1039,408,République populaire démocratique de Corée,2011,63738.26,7.05,1.73,0.44,4002.38,0.77,6924.90,43.0,NaN,NaN,43.0,43.0,0.0
1040,408,République populaire démocratique de Corée,2012,64724.38,7.13,1.75,0.45,4064.30,0.77,7032.04,44.0,NaN,NaN,44.0,44.0,0.0
1041,408,République populaire démocratique de Corée,2013,65525.90,7.18,1.77,0.45,4114.64,0.78,7119.12,44.0,NaN,NaN,44.0,44.0,0.0
1045,408,République populaire démocratique de Corée,2017,63694.78,6.84,1.68,0.43,4000.45,0.74,6918.40,43.0,0.0,NaN,43.0,43.0,0.0
1230,462,Maldives,2010,6346.07,48.09,12.67,2.79,367.94,5.73,755.99,7.0,NaN,6.0,5.0,NaN,0.0
1231,462,Maldives,2011,6767.15,49.51,13.04,2.87,392.31,5.90,806.06,8.0,NaN,7.0,5.0,NaN,0.0
1232,462,Maldives,2012,7004.33,49.52,13.04,2.87,406.04,5.90,834.29,8.0,NaN,7.0,5.0,NaN,0.0
1233,462,Maldives,2013,7588.63,51.88,13.59,3.00,439.02,6.17,902.44,10.0,NaN,10.0,5.0,NaN,0.0
1234,462,Maldives,2014,8041.05,52.86,13.84,3.06,464.74,6.29,956.60,9.0,NaN,9.0,6.0,NaN,0.0
1235,462,Maldives,2015,8940.29,56.23,14.76,3.26,517.78,6.69,1063.34,11.0,NaN,11.0,6.0,NaN,0.0
1236,462,Maldives,2016,10484.44,63.23,16.60,3.66,606.79,7.53,1247.73,12.0,NaN,12.0,8.0,NaN,0.0
1237,462,Maldives,2017,10030.14,58.17,15.24,3.37,580.70,6.91,1192.24,12.0,NaN,12.0,7.0,NaN,0.0
1238,462,Maldives,2018,10534.58,58.93,15.46,3.41,609.38,7.02,1254.02,13.0,NaN,13.0,8.0,NaN,0.0
1239,462,Maldives,2019,10924.47,59.33,15.50,3.44,633.84,7.03,1295.19,13.0,NaN,13.0,8.0,NaN,0.0
1240,462,Maldives,2020,10430.43,55.55,14.61,3.22,604.81,6.61,1240.98,8.0,0.0,11.0,8.0,NaN,0.0
1241,462,Maldives,2021,12827.56,67.40,17.60,3.91,743.74,7.99,1520.96,9.0,NaN,15.0,9.0,NaN,0.0

In [13]:
# On supprime ces 3 pays. En effet, le manque de données sur la production est rédhibitoire.
pays_a_supprimer = ['Maldives', 'République populaire démocratique de Corée', 'Djibouti']
Table_Volaille = Table_Volaille.loc[~Table_Volaille['Pays'].isin(pays_a_supprimer)]

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;" >
    <a name="C8" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>2.2 - Analyse exploratoire du fichier "Pop_Evol"</strong></a>
</div>

In [14]:
# Renommer la colonne Zone
Pop_Evol = Pop_Evol.rename(columns={'Zone': 'Pays'})

# On sélectionne uniquement la population totale:
pivoted_df = Pop_Evol.pivot(index=['Code zone (M49)', 'Pays', 'Année'], columns='Elément', values='Valeur')
pivoted_df = pivoted_df.reset_index()
Pop_Evol = pivoted_df[['Code zone (M49)','Pays','Année', 'Population totale en Milliers']]
Pop_Evol['Population totale en Milliers'] = Pop_Evol['Population totale en Milliers'] / 1000
Pop_Evol = Pop_Evol.rename(columns={'Population totale en Milliers':'Pop(Million)'})


# Après vérification, les Îles Anglo-Normandes n'ont aucunes données sur leur population. Je les supprime du DF
Pop_Evol = Pop_Evol[Pop_Evol["Pays"] != "Îles Anglo-Normandes"]

# Lecture des informations du fichier
infos_DF(Pop_Evol)

Elément  Code zone (M49)         Pays  Année  Pop(Million)
0                      4  Afghanistan   2000     19.542982
1                      4  Afghanistan   2001     19.688632
2                      4  Afghanistan   2002     21.000256

<class 'pandas.core.frame.DataFrame'>
Index: 5108 entries, 0 to 5129
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Code zone (M49)  5108 non-null   int64
 1   Pays             5108 non-null   object
 2   Année            5108 non-null   int64
 3   Pop(Million)     5108 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 199.5+ KB

Elément
Code zone (M49)    0
Pays               0
Année              0
Pop(Million)       0
dtype: int64

Elément
Code zone (M49)     238
Pays                238
Année                22
Pop(Million)       5099
dtype: int64

In [15]:
# Ajustement des Pays
Pays_absents(Pop_Evol,Pays_Etalon)

Elément  Code zone (M49)         Pays  Année  Pop(Million)
0                      4  Afghanistan   2000     19.542982
1                      4  Afghanistan   2001     19.688632

['Chine' 'Tchéquie' 'Palestine' 'Antilles néerlandaises (ex)'
 'Sint Maarten (partie néerlandaise)' 'Bonaire, Saint-Eustache et Saba'
 'Soudan (ex)' 'Îles Turques-et-Caïques'
 "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord"
 'Îles Wallis-et-Futuna' 'Serbie-et-Monténégro']

<div style="border: 10px solid RGB(0,0,0); width: 500px; background-color: RGB(110,15,15); margin: 0 auto; text-align: center;">
    <h3 style="margin: 10px; color: RGB(250,250,250);">Table de calcul de la croissance</h3>
</div>

In [16]:
#Table_Calcul_Croissance_Pop = Pop_Evol.pivot(index='Pays', columns='Année', values='Pop(Million)')
#TCCP = Table_Calcul_Croissance_Pop.copy()

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;" >
    <a name="C9" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>2.3 - Analyse exploratoire du fichier 'PIB_Hab'</strong></a>
</div>

In [17]:
# Remplacez 'Produit Intérieur Brut' 'par 'PIB'
PIB_Hab['Produit'] = 'PIB'

# Supprimer les lignes avec les années de 2000 à 2009
An_Sup = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]
PIB_Hab = PIB_Hab.loc[~PIB_Hab["Année"].isin(An_Sup)]

# Agrégez les colonnes 'Elément' et 'Unité' en une nouvelle colonne 'Items'
PIB_Hab['Items'] = PIB_Hab['Produit']+ " / " + PIB_Hab['PIB - Elements']
PIB_Hab = PIB_Hab.rename(columns={'Zone': 'Pays'})
PIB_Hab= PIB_Hab.pivot(index=['Code zone (M49)', 'Pays','Année'], columns='Items', values='Valeur' )
PIB_Hab = PIB_Hab.reset_index()

# Lecture des informations du fichier
infos_DF(PIB_Hab)

Items,Code zone (M49),Pays,Année,PIB / Croissance annuelle US$ %,PIB / Croissance annuelle US$ par habitant %,PIB / Valeur US $ Millions d’USD,PIB / Valeur US $ par habitant USD
0,4,Afghanistan,2010,26.767749,23.150554,14698.88968,521.428191
1,4,Afghanistan,2011,18.040854,13.765090,17350.69495,593.203249
2,4,Afghanistan,2012,10.292408,5.885553,19136.49934,628.116539

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2746 entries, 0 to 2745
Data columns (total 7 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Code zone (M49)                               2746 non-null   int64
 1   Pays                                          2746 non-null   object
 2   Année                                         2746 non-null   int64
 3   PIB / Croissance annuelle US$ %               2746 non-null   float64
 4   PIB / Croissance annuelle US$ par habitant %  2746 non-null   float64
 5   PIB / Valeur US $ Millions d’USD              2746 non-null   float64
 6   PIB / Valeur US $ par habitant USD            2746 non-null   float64
dtypes: float64(4), int64(2), object(1)
memory usage: 150.3+ KB

Items
Code zone (M49)                                 0
Pays                                            0
Année                                           0
PIB / Croissance annuelle US$ %                 0
PIB / Croissance annuelle US$ par habitant %    0
PIB / Valeur US $ Millions d’USD                0
PIB / Valeur US $ par habitant USD              0
dtype: int64

Items
Code zone (M49)                                  212
Pays                                             212
Année                                             13
PIB / Croissance annuelle US$ %                 2745
PIB / Croissance annuelle US$ par habitant %    2746
PIB / Valeur US $ Millions d’USD                2746
PIB / Valeur US $ par habitant USD              2746
dtype: int64

In [18]:
# Ordre souhaité des colonnes
new_order = ['Code zone (M49)', 'Pays', 'Année', 'PIB / Croissance annuelle US$ par habitant %',
             'PIB / Croissance annuelle US$ %', 'PIB / Valeur US $ par habitant USD', 'PIB / Valeur US $ Millions d’USD']

# Réorganiser les colonnes
PIB_Hab = PIB_Hab.reindex(columns=new_order)

In [19]:
# Ajustement des Pays
Pays_absents(PIB_Hab,Pays_Etalon)

Items,Code zone (M49),Pays,Année,PIB / Croissance annuelle US$ par habitant %,PIB / Croissance annuelle US$ %,PIB / Valeur US $ par habitant USD,PIB / Valeur US $ Millions d’USD
0,4,Afghanistan,2010,23.150554,26.767749,521.428191,14698.88968
1,4,Afghanistan,2011,13.765090,18.040854,593.203249,17350.69495

['Chine' 'Tchéquie' 'Palestine' 'Antilles néerlandaises (ex)'
 'Sint Maarten (partie néerlandaise)' 'Îles Turques-et-Caïques'
 "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord"]

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;" >
    <a name="C11" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>2.5 - Analyse exploratoire du fichier 'StabPol.csv'</strong></a>
</div>

In [20]:
# Supprimer les lignes avec les années de 2000 à 2009
# Renommer la colonne Zone
StabPol = StabPol.rename(columns={'Country Name': 'Pays','Country Code':'Alpha-3 code'})
An_Sup = [2000, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]
StabPol = StabPol.loc[~StabPol["Année"].isin(An_Sup)]

In [21]:
StabPol[StabPol.isna().any(axis=1)]

                         Pays Alpha-3 code  Année  Indice Stabilité politique
1000             Cook Islands          COK   2011                         NaN
1001             Cook Islands          COK   2012                         NaN
1002             Cook Islands          COK   2013                         NaN
1003             Cook Islands          COK   2014                         NaN
1004             Cook Islands          COK   2015                         NaN
1005             Cook Islands          COK   2016                         NaN
1006             Cook Islands          COK   2017                         NaN
2099  Jersey, Channel Islands          JEY   2010                         NaN
3049     Netherlands Antilles          ANT   2014                         NaN
3050     Netherlands Antilles          ANT   2015                         NaN
3051     Netherlands Antilles          ANT   2016                         NaN
3052     Netherlands Antilles          ANT   2017                         NaN
3053     Netherlands Antilles          ANT   2018                         NaN
3054     Netherlands Antilles          ANT   2019                         NaN
3055     Netherlands Antilles          ANT   2020                         NaN
3056     Netherlands Antilles          ANT   2021                         NaN
3057     Netherlands Antilles          ANT   2022                         NaN
3156                     Niue          NIU   2011                         NaN
3157                     Niue          NIU   2012                         NaN
3158                     Niue          NIU   2013                         NaN
3159                     Niue          NIU   2014                         NaN
3160                     Niue          NIU   2015                         NaN
3161                     Niue          NIU   2016                         NaN
3162                     Niue          NIU   2017                         NaN
3881              South Sudan          SSD   2010                         NaN

In [22]:
# Avec plusieurs données manquantes et n'étant pas des cibles pour l'entreprise, nous supprimons 'Niue' et 'Cook Islands' de notre DF
# Les antilles néerlandaisesont été dissoutes le 10 Octobre 2010. On les supprime de notre DF
Pays_Sup = ['Netherlands Antilles', 'Niue', 'Cook Islands']
StabPol = StabPol[~StabPol['Pays'].isin(Pays_Sup)]


# N'ayant qu'une donnée manquante, nous conservons de 'Jersey, Channel Islands' et 'South Sudan'
# Calculer la moyenne des valeurs de 2011 à 2013 pour imputer 2010
# Filtre des périodes pour 'SSD' et 'JEY'
periode_SSD = StabPol[(StabPol['Alpha-3 code'] == 'SSD') & (StabPol['Année'] >= 2011) & (StabPol['Année'] <= 2013)]
periode_JEY = StabPol[(StabPol['Alpha-3 code'] == 'JEY') & (StabPol['Année'] >= 2011) & (StabPol['Année'] <= 2014)]

# Calcul moyenne 'Indice Stabilité politique' pour 'JEY' et 'SSD'
moyenne_SSD = periode_SSD['Indice Stabilité politique'].mean()
moyenne_JEY = periode_JEY['Indice Stabilité politique'].mean()

# Imputation des valeurs
StabPol.loc[(StabPol['Alpha-3 code'] == 'JEY') & (StabPol['Année'] == 2010), 'Indice Stabilité politique'] = moyenne_JEY
StabPol.loc[(StabPol['Alpha-3 code'] == 'SSD') & (StabPol['Année'] == 2010), 'Indice Stabilité politique'] = moyenne_SSD

In [23]:
infos_DF(StabPol)

           Pays Alpha-3 code  Année  Indice Stabilité politique
9   Afghanistan          AFG   2010                   -2.579152
10  Afghanistan          AFG   2011                   -2.502060
11  Afghanistan          AFG   2012                   -2.418561

<class 'pandas.core.frame.DataFrame'>
Index: 2743 entries, 9 to 4707
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Pays                        2743 non-null   object
 1   Alpha-3 code                2743 non-null   object
 2   Année                       2743 non-null   int64
 3   Indice Stabilité politique  2743 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 107.1+ KB

Pays                          0
Alpha-3 code                  0
Année                         0
Indice Stabilité politique    0
dtype: int64

Pays                           211
Alpha-3 code                   211
Année                           13
Indice Stabilité politique    2671
dtype: int64

<div style="border: 10px solid RGB(0,0,0); width: 500px; background-color: RGB(110,15,15); margin: 0 auto; text-align: center;">
    <h3 style="margin: 10px; color: RGB(250,250,250);">Concordance des pays</h3>
</div>

In [24]:
# Ajustement des Pays
Pays_absents(StabPol,Pays_Etalon,'En')

           Pays Alpha-3 code  Année  Indice Stabilité politique
9   Afghanistan          AFG   2010                   -2.579152
10  Afghanistan          AFG   2011                   -2.502060

['Bahamas, The' 'Bolivia' 'Congo, Dem. Rep.' 'Congo, Rep.' "Cote d'Ivoire"
 'Egypt, Arab Rep.' 'Gambia, The' 'Hong Kong SAR, China'
 'Iran, Islamic Rep.' 'Jersey, Channel Islands'
 "Korea, Dem. People's Rep." 'Korea, Rep.' 'Kyrgyz Republic' 'Lao PDR'
 'Macao SAR, China' 'Micronesia, Fed. Sts.' 'Moldova' 'North Macedonia'
 'Reunion' 'Slovak Republic' 'St. Kitts and Nevis' 'St. Lucia'
 'St. Vincent and the Grenadines' 'Taiwan, China' 'Tanzania' 'Turkiye'
 'United States' 'Venezuela, RB' 'Vietnam' 'Virgin Islands (U.S.)'
 'West Bank and Gaza' 'Yemen, Rep.']

In [25]:
# Jointure pour obtenir les pays en français
StabPol = StabPol.rename(columns={'Pays':'Country'})
StabPol =pd.merge(StabPol,Pays_Etalon[['Alpha-3 code', 'Pays','Numeric code']], on=['Alpha-3 code'], how='left')
StabPol = StabPol.rename(columns={'Numeric code':'Code zone (M49)'})

# Ré-ajustement des Pays en français
Pays_absents(StabPol,Pays_Etalon)

# Vérification des valeurs nulles
display(StabPol[StabPol.isnull().any(axis=1)].head(3))

# Le Kosovo fait partie de la Serbie (Province). Nous supprimons l'information.
StabPol = StabPol[StabPol['Country'] != 'Kosovo']
message = "Le Kosovo fait partie de la Serbie (Province). Nous supprimons l'information."
Text_message(message)

# Vérification
Pays_absents(StabPol,Pays_Etalon)

,Country,Alpha-3 code,Année,Indice Stabilité politique,Pays,Code zone (M49)
0,Afghanistan,AFG,2010,-2.579152,Afghanistan,4.0
1,Afghanistan,AFG,2011,-2.502060,Afghanistan,4.0

[nan]

,Country,Alpha-3 code,Année,Indice Stabilité politique,Pays,Code zone (M49)
1313,Kosovo,XKX,2010,-1.044821,NaN,NaN
1314,Kosovo,XKX,2011,-1.042147,NaN,NaN
1315,Kosovo,XKX,2012,-1.038502,NaN,NaN

,Country,Alpha-3 code,Année,Indice Stabilité politique,Pays,Code zone (M49)
0,Afghanistan,AFG,2010,-2.579152,Afghanistan,4.0
1,Afghanistan,AFG,2011,-2.502060,Afghanistan,4.0

[]

In [26]:
# On renomme les deux pays suivants pour la cohérence des jointures
StabPol.loc[StabPol['Country']== 'Czechia', 'Pays'] = "Tchéquie"
StabPol.loc[StabPol['Country']== 'United Kingdom', 'Pays'] = "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord"

<div style="background-color: RGB(51,153,153); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(0,0,0); padding: 5px;" >
    <a name="C12" style="font-size: 20px; font-weight: bold; line-height: 1.5;padding: 20px; font-family: 'Calibri'; color: RGB(0,0,0);"><strong>2.6 - Analyse exploratoire du fichier 'Protein.csv'</strong></a>
</div>

In [27]:
# Renommer la colonne 'Zone' -> 'Pays'
Protein = Protein.rename(columns={'Zone': 'Pays'})

# Supprimer les lignes avec les années de 2000 à 2009
An_Sup = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]
Protein = Protein.loc[~Protein["Année"].isin(An_Sup)]

# Pivoter la table et renommer les colonnes
Protein = Protein.pivot(index=['Code zone (M49)', 'Pays','Année'], columns='Produit', values='Valeur' )
Protein = Protein.reset_index()
Protein = Protein.rename(columns={'Disponibilités protéines moyennes d’origine animale (g/personne/jour) (moyenne sur 3 ans)'
                                  :'Moy_Prot_Animale',
                                  'Disponibilités protéiques moyennes (g/personne/jour) (moyenne sur 3 ans)':'Moy_Prot'})

# Ajout des proportions de protéines animales par rapport aux totaux des protéines
Protein['%Prot_animale']=round(Protein['Moy_Prot_Animale'] / Protein['Moy_Prot'],2)

#Lecture des infos du fichier
infos_DF(Protein)

Produit,Code zone (M49),Pays,Année,Moy_Prot_Animale,Moy_Prot,%Prot_animale
0,4,Afghanistan,2010,11.0,58.0,0.19
1,4,Afghanistan,2011,11.0,58.0,0.19
2,4,Afghanistan,2012,11.0,57.3,0.19

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1810 entries, 0 to 1809
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Code zone (M49)   1810 non-null   int64
 1   Pays              1810 non-null   object
 2   Année             1810 non-null   int64
 3   Moy_Prot_Animale  1810 non-null   float64
 4   Moy_Prot          1810 non-null   float64
 5   %Prot_animale     1810 non-null   float64
dtypes: float64(3), int64(2), object(1)
memory usage: 85.0+ KB

Produit
Code zone (M49)     0
Pays                0
Année               0
Moy_Prot_Animale    0
Moy_Prot            0
%Prot_animale       0
dtype: int64

Produit
Code zone (M49)     188
Pays                188
Année                10
Moy_Prot_Animale    316
Moy_Prot            403
%Prot_animale        70
dtype: int64

<div style="border: 10px solid RGB(0,0,0); width: 500px; background-color: RGB(110,15,15); margin: 0 auto; text-align: center;">
    <h3 style="margin: 10px; color: RGB(250,250,250);">Concordance des pays</h3>
</div>

In [28]:
# Ajustement des Pays
Pays_absents(Protein,Pays_Etalon)

Produit,Code zone (M49),Pays,Année,Moy_Prot_Animale,Moy_Prot,%Prot_animale
0,4,Afghanistan,2010,11.0,58.0,0.19
1,4,Afghanistan,2011,11.0,58.0,0.19

['Chine' 'Tchéquie' "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord"]

<div style="background-color: RGB(0,0,0); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(51,153,153);padding: 5px;">
    <a name="C13" style="margin: auto; padding: 20px; line-height: 2.5; color:RGB(51,153,153); font-size: 20px; font-weight: bold;" >3 - Sauvegarde des tables nettoyées et préparées</a>
</div>

In [29]:
Table_Volaille.to_csv('Volaille_NP.csv', index=False)
Pop_Evol.to_csv('Pop_Evol_NP.csv', index=False)
PIB_Hab.to_csv('PIB_Hab_NP.csv', index=False)
StabPol.to_csv('StabPol_NP.csv', index=False)
Protein.to_csv('Protein_NP.csv', index=False)

<div style="background-color: RGB(0,0,0); margin-top: 10px; margin-bottom: 10px; border: 5px solid RGB(51,153,153);padding: 5px;">
    <a name="C14" style="margin: auto; padding: 20px; line-height: 2.5; color:RGB(51,153,153); font-size: 20px; font-weight: bold;" >4 - Jointures des tables</a>
</div>

In [30]:
######################################## Ajout de variables pour l'analyse: ##########################################
# Taux d'importation
Table_Volaille['%import'] = round(((Table_Volaille['Importations - Quantité / Milliers de tonnes'] 
                            / Table_Volaille['Disponibilité intérieure / Milliers de tonnes']) *100),2)
# Taux d'exportation
Table_Volaille['%export'] = round(((Table_Volaille['Exportations - Quantité / Milliers de tonnes'] 
                            / Table_Volaille['Disponibilité intérieure / Milliers de tonnes']) *100),2)
# Taux de production
Table_Volaille['%prod'] = round(((Table_Volaille['Production / Milliers de tonnes'] 
                            / Table_Volaille['Disponibilité intérieure / Milliers de tonnes']) *100),2)

In [31]:
# Jointures des tables
Table_Volaille_F = pd.merge(Table_Volaille,Pop_Evol, on=['Code zone (M49)','Pays','Année'], how='left')
#Table_Volaille_AN = pd.merge(Table_Volaille_AN,Imp_Export_Pivot_AN, on=['Code zone (M49)','Pays','Année'], how='left')
DF_Fin = pd.merge(Table_Volaille_F,PIB_Hab, on=['Code zone (M49)','Pays','Année'], how='left')
DF_Fin = pd.merge(DF_Fin,StabPol, on=['Code zone (M49)','Pays','Année'], how='left')
DF_Fin = pd.merge(DF_Fin,Protein, on=['Code zone (M49)','Pays','Année'], how='left')

# Réindexation
DF_Fin = DF_Fin.reset_index(drop=True)

DF_Fin = DF_Fin.sort_values(by='Pays', ascending=True)
DF_Fin = DF_Fin.drop(['Code zone (M49)','Country','Alpha-3 code'], axis=1)

# Définir 'Pays' comme index
DF_Fin = DF_Fin.set_index('Pays')

infos_DF(DF_Fin)

,Année,Disponibilité alimentaire (Kcal),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de matière grasse en quantité (t),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité de protéines en quantité (t),Disponibilité intérieure / Milliers de tonnes,Exportations - Quantité / Milliers de tonnes,...,%prod,Pop(Million),PIB / Croissance annuelle US$ par habitant %,PIB / Croissance annuelle US$ %,PIB / Valeur US $ par habitant USD,PIB / Valeur US $ Millions d’USD,Indice Stabilité politique,Moy_Prot_Animale,Moy_Prot,%Prot_animale
Pays,,,,,,,,,,,,,,,,,,,,,
Afghanistan,2010,88908.07,8.64,2.29,0.50,5150.16,1.03,10625.60,65.0,4.0,...,43.08,28.189672,23.150554,26.767749,521.428191,14698.88968,-2.579152,11.0,58.0,0.19
Afghanistan,2020,88288.39,6.21,1.64,0.36,5115.13,0.74,10542.19,64.0,0.0,...,43.75,38.972230,3.265362,6.553742,516.866543,20143.44179,-2.702632,NaN,NaN,NaN
Afghanistan,2019,94490.39,6.85,1.81,0.40,5471.99,0.82,11286.68,69.0,6.0,...,40.58,37.769499,-0.305564,2.636658,500.522664,18904.49026,-2.652407,10.0,56.3,0.18

<class 'pandas.core.frame.DataFrame'>
Index: 2128 entries, Afghanistan to Îles Salomon
Data columns (total 26 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Année                                                          2128 non-null   int64
 1   Disponibilité alimentaire (Kcal)                               2128 non-null   float64
 2   Disponibilité alimentaire (Kcal/personne/jour)                 2128 non-null   float64
 3   Disponibilité alimentaire en quantité (kg/personne/an)         2128 non-null   float64
 4   Disponibilité de matière grasse en quantité (g/personne/jour)  2128 non-null   float64
 5   Disponibilité de matière grasse en quantité (t)                2128 non-null   float64
 6   Disponibilité de protéines en quantité (g/personne/jour)       2128 non-null   float64
 7   Disponibilité de protéines en quantité (t)                     2128 non-null   float64
 8   Disponibilité intérieure / Milliers de tonnes                  2128 non-null   float64
 9   Exportations - Quantité / Milliers de tonnes                   2128 non-null   float64
 10  Importations - Quantité / Milliers de tonnes                   2128 non-null   float64
 11  Nourriture / Milliers de tonnes                                2128 non-null   float64
 12  Production / Milliers de tonnes                                2128 non-null   float64
 13  Résidus / Milliers de tonnes                                   2128 non-null   float64
 14  %import                                                        2128 non-null   float64
 15  %export                                                        2128 non-null   float64
 16  %prod                                                          2128 non-null   float64
 17  Pop(Million)                                                   2128 non-null   float64
 18  PIB / Croissance annuelle US$ par habitant %                   2116 non-null   float64
 19  PIB / Croissance annuelle US$ %                                2116 non-null   float64
 20  PIB / Valeur US $ par habitant USD                             2116 non-null   float64
 21  PIB / Valeur US $ Millions d’USD                               2116 non-null   float64
 22  Indice Stabilité politique                                     2104 non-null   float64
 23  Moy_Prot_Animale                                               1761 non-null   float64
 24  Moy_Prot                                                       1761 non-null   float64
 25  %Prot_animale                                                  1761 non-null   float64
dtypes: float64(25), int64(1)
memory usage: 448.9+ KB

Année                                                              0
Disponibilité alimentaire (Kcal)                                   0
Disponibilité alimentaire (Kcal/personne/jour)                     0
Disponibilité alimentaire en quantité (kg/personne/an)             0
Disponibilité de matière grasse en quantité (g/personne/jour)      0
Disponibilité de matière grasse en quantité (t)                    0
Disponibilité de protéines en quantité (g/personne/jour)           0
Disponibilité de protéines en quantité (t)                         0
Disponibilité intérieure / Milliers de tonnes                      0
Exportations - Quantité / Milliers de tonnes                       0
Importations - Quantité / Milliers de tonnes                       0
Nourriture / Milliers de tonnes                                    0
Production / Milliers de tonnes                                    0
Résidus / Milliers de tonnes                                       0
%import                                                            0
%export                                                            0
%prod                                                              0
Pop(Million)                                                       0
PIB / Croissance annuelle US$ par habitant %                      12
PIB / Croissance annuelle US$ %                                   12
PIB / Valeur US $ par habitant USD                                12
PIB / Valeur US $ Millions d’USD                                  12
Indice Stabilité politique                                        24
Moy_Prot_Animale                                                 367
Moy_Prot                                                         367
%Prot_animale                                                    367
dtype: int64

Année                                                              12
Disponibilité alimentaire (Kcal)                                 2128
Disponibilité alimentaire (Kcal/personne/jour)                   1981
Disponibilité alimentaire en quantité (kg/personne/an)           1696
Disponibilité de matière grasse en quantité (g/personne/jour)     959
Disponibilité de matière grasse en quantité (t)                  2126
Disponibilité de protéines en quantité (g/personne/jour)         1333
Disponibilité de protéines en quantité (t)                       2128
Disponibilité intérieure / Milliers de tonnes                     775
Exportations - Quantité / Milliers de tonnes                      314
Importations - Quantité / Milliers de tonnes                      378
Nourriture / Milliers de tonnes                                   754
Production / Milliers de tonnes                                   716
Résidus / Milliers de tonnes                                       57
%import                                                          1216
%export                                                           834
%prod                                                            1380
Pop(Million)                                                     2128
PIB / Croissance annuelle US$ par habitant %                     2116
PIB / Croissance annuelle US$ %                                  2116
PIB / Valeur US $ par habitant USD                               2116
PIB / Valeur US $ Millions d’USD                                 2116
Indice Stabilité politique                                       2087
Moy_Prot_Animale                                                  299
Moy_Prot                                                          383
%Prot_animale                                                      70
dtype: int64

<div style="border: 10px solid RGB(0,0,0); width: 500px; background-color: RGB(110,15,15); margin: 0 auto; text-align: center;">
    <h3 style="margin: 10px; color: RGB(250,250,250);">Après avoir vérifié les valeurs manquantes, je réalise les traitements nécessaires</h3>
</div>

In [32]:
# Suppression des années 2020 et 2021 (Pas de données sur les protéines animales)
DF_Fin[DF_Fin['Moy_Prot_Animale'].isna()]['Année'].unique()
DF_Fin = DF_Fin[~DF_Fin['Année'].isin([2020, 2021])]

In [33]:
# Stabilité politique pour la Nouvelle-Calédonie et la Polynésie française
# Récupérer l'indice de stabilité politique de la France
IS_france = DF_Fin.loc['France', 'Indice Stabilité politique']
# Imputation de l'indice de Stabilité de la France pour les deux territoires
DF_Fin.loc['Nouvelle-Calédonie', 'Indice Stabilité politique'] = IS_france.values
DF_Fin.loc['Polynésie française', 'Indice Stabilité politique'] = IS_france.values

In [34]:
# Imputation des données concernant le PIB pour Taiwan:
# Source : https://fr.tradingeconomics.com/taiwan/full-year-gdp-growth
Pib_valeur = np.array([444.30,483.96, 495.54,512.96,535.33,534.47,543,590.78,609.25,611.34])
Pib_crois = np.array([10.25,3.67,2.22,2.48,4.72,1.47,2.17,3.31,2.79,3.06])
# Source : https://fr.statista.com/statistiques/1310481/taiwan-pib-habitant/
Pib_Hab = np.array([19181.36,20838.59,21256.36,21945.46,22844.32,22752.99,23070.73,25061.62,25825.57,25935.90])

DF_Fin.loc['Chine, Taiwan Province de', 'PIB / Valeur US $ Millions d’USD'] = Pib_valeur
DF_Fin.loc['Chine, Taiwan Province de', 'PIB / Croissance annuelle US$ %'] = Pib_crois
DF_Fin.loc['Chine, Taiwan Province de', 'PIB / Valeur US $ par habitant USD'] = Pib_Hab

#Ajout du Pib/Hab 2009:
Pib_Hab = np.array([16904.54,19181.36,20838.59,21256.36,21945.46,22844.32,22752.99,23070.73,25061.62,25825.57,25935.90])
# Calcul de la croissance Pib.Hab de 2010 à 2019
Pib_CroisHab = []
for i in range(1, len(Pib_Hab)):
    result = round((((Pib_Hab[i] * 100) / Pib_Hab[i-1]) - 100),2)
    Pib_CroisHab.append(result)
Pib_CroisHab=np.array(Pib_CroisHab)
DF_Fin.loc['Chine, Taiwan Province de', 'PIB / Croissance annuelle US$ par habitant %'] = Pib_CroisHab

In [35]:
# Imputation des données concernant les proteînes animales pour le Burundi:

# Vu lévolution des Protéines animales du burundi, je décide d'imputer les valeurs de 2013 pour 2010, 2011 et 2012.
BMPA_2013 = DF_Fin.loc['Burundi', 'Moy_Prot_Animale'][DF_Fin.loc['Burundi', 'Année'] == 2013].values[0]
BMP_2013 = DF_Fin.loc['Burundi', 'Moy_Prot'][DF_Fin.loc['Burundi', 'Année'] == 2013].values[0]
BPA_2013 = DF_Fin.loc['Burundi', '%Prot_animale'][DF_Fin.loc['Burundi', 'Année'] == 2013].values[0]

DF_Fin.loc['Burundi', 'Moy_Prot_Animale'][DF_Fin.loc['Burundi', 'Année'] == 2012] = BMPA_2013
DF_Fin.loc['Burundi', 'Moy_Prot_Animale'][DF_Fin.loc['Burundi', 'Année'] == 2011] = BMPA_2013
DF_Fin.loc['Burundi', 'Moy_Prot_Animale'][DF_Fin.loc['Burundi', 'Année'] == 2010] = BMPA_2013

DF_Fin.loc['Burundi', 'Moy_Prot'][DF_Fin.loc['Burundi', 'Année'] == 2012] = BMP_2013
DF_Fin.loc['Burundi', 'Moy_Prot'][DF_Fin.loc['Burundi', 'Année'] == 2011] = BMP_2013
DF_Fin.loc['Burundi', 'Moy_Prot'][DF_Fin.loc['Burundi', 'Année'] == 2010] = BMP_2013

DF_Fin.loc['Burundi', '%Prot_animale'][DF_Fin.loc['Burundi', 'Année'] == 2012] = BPA_2013
DF_Fin.loc['Burundi', '%Prot_animale'][DF_Fin.loc['Burundi', 'Année'] == 2011] = BPA_2013
DF_Fin.loc['Burundi', '%Prot_animale'][DF_Fin.loc['Burundi', 'Année'] == 2010] = BPA_2013

In [36]:
infos_DF(DF_Fin)

,Année,Disponibilité alimentaire (Kcal),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de matière grasse en quantité (t),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité de protéines en quantité (t),Disponibilité intérieure / Milliers de tonnes,Exportations - Quantité / Milliers de tonnes,...,%prod,Pop(Million),PIB / Croissance annuelle US$ par habitant %,PIB / Croissance annuelle US$ %,PIB / Valeur US $ par habitant USD,PIB / Valeur US $ Millions d’USD,Indice Stabilité politique,Moy_Prot_Animale,Moy_Prot,%Prot_animale
Pays,,,,,,,,,,,,,,,,,,,,,
Afghanistan,2010,88908.07,8.64,2.29,0.50,5150.16,1.03,10625.60,65.0,4.0,...,43.08,28.189672,23.150554,26.767749,521.428191,14698.88968,-2.579152,11.0,58.0,0.19
Afghanistan,2019,94490.39,6.85,1.81,0.40,5471.99,0.82,11286.68,69.0,6.0,...,40.58,37.769499,-0.305564,2.636658,500.522664,18904.49026,-2.652407,10.0,56.3,0.18
Afghanistan,2018,73734.20,5.51,1.46,0.32,4269.94,0.66,8808.96,53.0,0.0,...,54.72,36.686784,-5.299079,-2.526962,502.056771,18418.84830,-2.753262,10.3,57.3,0.18

<class 'pandas.core.frame.DataFrame'>
Index: 1764 entries, Afghanistan to Îles Salomon
Data columns (total 26 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Année                                                          1764 non-null   int64
 1   Disponibilité alimentaire (Kcal)                               1764 non-null   float64
 2   Disponibilité alimentaire (Kcal/personne/jour)                 1764 non-null   float64
 3   Disponibilité alimentaire en quantité (kg/personne/an)         1764 non-null   float64
 4   Disponibilité de matière grasse en quantité (g/personne/jour)  1764 non-null   float64
 5   Disponibilité de matière grasse en quantité (t)                1764 non-null   float64
 6   Disponibilité de protéines en quantité (g/personne/jour)       1764 non-null   float64
 7   Disponibilité de protéines en quantité (t)                     1764 non-null   float64
 8   Disponibilité intérieure / Milliers de tonnes                  1764 non-null   float64
 9   Exportations - Quantité / Milliers de tonnes                   1764 non-null   float64
 10  Importations - Quantité / Milliers de tonnes                   1764 non-null   float64
 11  Nourriture / Milliers de tonnes                                1764 non-null   float64
 12  Production / Milliers de tonnes                                1764 non-null   float64
 13  Résidus / Milliers de tonnes                                   1764 non-null   float64
 14  %import                                                        1764 non-null   float64
 15  %export                                                        1764 non-null   float64
 16  %prod                                                          1764 non-null   float64
 17  Pop(Million)                                                   1764 non-null   float64
 18  PIB / Croissance annuelle US$ par habitant %                   1764 non-null   float64
 19  PIB / Croissance annuelle US$ %                                1764 non-null   float64
 20  PIB / Valeur US $ par habitant USD                             1764 non-null   float64
 21  PIB / Valeur US $ Millions d’USD                               1764 non-null   float64
 22  Indice Stabilité politique                                     1764 non-null   float64
 23  Moy_Prot_Animale                                               1764 non-null   float64
 24  Moy_Prot                                                       1764 non-null   float64
 25  %Prot_animale                                                  1764 non-null   float64
dtypes: float64(25), int64(1)
memory usage: 436.6+ KB

Année                                                            0
Disponibilité alimentaire (Kcal)                                 0
Disponibilité alimentaire (Kcal/personne/jour)                   0
Disponibilité alimentaire en quantité (kg/personne/an)           0
Disponibilité de matière grasse en quantité (g/personne/jour)    0
Disponibilité de matière grasse en quantité (t)                  0
Disponibilité de protéines en quantité (g/personne/jour)         0
Disponibilité de protéines en quantité (t)                       0
Disponibilité intérieure / Milliers de tonnes                    0
Exportations - Quantité / Milliers de tonnes                     0
Importations - Quantité / Milliers de tonnes                     0
Nourriture / Milliers de tonnes                                  0
Production / Milliers de tonnes                                  0
Résidus / Milliers de tonnes                                     0
%import                                                          0
%export                                                          0
%prod                                                            0
Pop(Million)                                                     0
PIB / Croissance annuelle US$ par habitant %                     0
PIB / Croissance annuelle US$ %                                  0
PIB / Valeur US $ par habitant USD                               0
PIB / Valeur US $ Millions d’USD                                 0
Indice Stabilité politique                                       0
Moy_Prot_Animale                                                 0
Moy_Prot                                                         0
%Prot_animale                                                    0
dtype: int64

Année                                                              10
Disponibilité alimentaire (Kcal)                                 1764
Disponibilité alimentaire (Kcal/personne/jour)                   1655
Disponibilité alimentaire en quantité (kg/personne/an)           1448
Disponibilité de matière grasse en quantité (g/personne/jour)     859
Disponibilité de matière grasse en quantité (t)                  1762
Disponibilité de protéines en quantité (g/personne/jour)         1174
Disponibilité de protéines en quantité (t)                       1764
Disponibilité intérieure / Milliers de tonnes                     688
Exportations - Quantité / Milliers de tonnes                      282
Importations - Quantité / Milliers de tonnes                      337
Nourriture / Milliers de tonnes                                   667
Production / Milliers de tonnes                                   634
Résidus / Milliers de tonnes                                       54
%import                                                          1043
%export                                                           717
%prod                                                            1180
Pop(Million)                                                     1764
PIB / Croissance annuelle US$ par habitant %                     1764
PIB / Croissance annuelle US$ %                                  1764
PIB / Valeur US $ par habitant USD                               1764
PIB / Valeur US $ Millions d’USD                                 1764
Indice Stabilité politique                                       1731
Moy_Prot_Animale                                                  299
Moy_Prot                                                          383
%Prot_animale                                                      70
dtype: int64

In [37]:
DF_Fin = DF_Fin.reset_index()
Pays_absents(DF_Fin,Pays_Etalon)
# Mise en conformité des Pays
Concordance_pays = {"Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": 'Royaume-Uni', 'Tchéquie':'République Tchèque'}
DF_Fin['Pays'] = DF_Fin['Pays'].replace(Concordance_pays)
Titre_message("Concordance avec le fichier 'Etalon'")
Pays_absents(DF_Fin,Pays_Etalon)

,Pays,Année,Disponibilité alimentaire (Kcal),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de matière grasse en quantité (t),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité de protéines en quantité (t),Disponibilité intérieure / Milliers de tonnes,...,%prod,Pop(Million),PIB / Croissance annuelle US$ par habitant %,PIB / Croissance annuelle US$ %,PIB / Valeur US $ par habitant USD,PIB / Valeur US $ Millions d’USD,Indice Stabilité politique,Moy_Prot_Animale,Moy_Prot,%Prot_animale
0,Afghanistan,2010,88908.07,8.64,2.29,0.5,5150.16,1.03,10625.60,65.0,...,43.08,28.189672,23.150554,26.767749,521.428191,14698.88968,-2.579152,11.0,58.0,0.19
1,Afghanistan,2019,94490.39,6.85,1.81,0.4,5471.99,0.82,11286.68,69.0,...,40.58,37.769499,-0.305564,2.636658,500.522664,18904.49026,-2.652407,10.0,56.3,0.18

["Royaume-Uni de Grande-Bretagne et d'Irlande du Nord" 'Tchéquie']

,Pays,Année,Disponibilité alimentaire (Kcal),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de matière grasse en quantité (t),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité de protéines en quantité (t),Disponibilité intérieure / Milliers de tonnes,...,%prod,Pop(Million),PIB / Croissance annuelle US$ par habitant %,PIB / Croissance annuelle US$ %,PIB / Valeur US $ par habitant USD,PIB / Valeur US $ Millions d’USD,Indice Stabilité politique,Moy_Prot_Animale,Moy_Prot,%Prot_animale
0,Afghanistan,2010,88908.07,8.64,2.29,0.5,5150.16,1.03,10625.60,65.0,...,43.08,28.189672,23.150554,26.767749,521.428191,14698.88968,-2.579152,11.0,58.0,0.19
1,Afghanistan,2019,94490.39,6.85,1.81,0.4,5471.99,0.82,11286.68,69.0,...,40.58,37.769499,-0.305564,2.636658,500.522664,18904.49026,-2.652407,10.0,56.3,0.18

[]

<div style="border: 10px solid RGB(0,0,0); width: 500px; background-color: RGB(110,15,15); margin: 0 auto; text-align: center;">
    <h2 style="margin: 10px; color: RGB(250,250,250);">Enregistrement de la table</h2>
</div>

In [38]:
DF_Fin.to_csv('DF_VOLAILLE.csv', index=False)